# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: AnDO Tests

on:
  # Run one build a month at 01:00
  schedule:
  - cron:  '0 1 1 * *'
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  run-test:
    name: Running tests using miniconda
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: deptest-${{ matrix.python-version }}
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Show conda details
        run: |
          conda info
          conda list
          which python
          conda --version
      - name: Install git-annex on OSX
        if: runner.os == 'macOS'
        run: |
          brew install git-annex
      - name: Install Conda dependencies
        run: |
          conda install -c conda-forge datalad
          conda install pip pytest
      - name: Configure git-annex
        run: |
          git config --global user.email "AnDOTest@githubactions.com"
          git config --global user.name "Github Actions"
      - name: Install pip dependencies
        run: |
          pip install -e .
      - name: Run tests
        run: |
          pytest
