# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: BEP032tools Tests

on:
  # Run one build a month at 01:00
  schedule:
  - cron:  '0 1 1 * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-test:
    name: Running tests using miniconda
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: deptest-${{ matrix.python-version }}
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Show conda details
        run: |
          conda info
          conda list
          which python
          conda --version

      - name: Install git-annex on OSX
        if: runner.os == 'macOS'
        run: |
          brew install git-annex

      - name: Install git-annex on Windows
        if: runner.os == 'Windows'
        run: |
          choco install git.install
          choco install --ignore-checksums git-annex

      - name: Install other conda dependencies
        run: |
          conda install -c conda-forge datalad
          conda install pip pytest

      - name: Configure git-annex
        run: |
          git config --global user.email "BEP032toolsTest@githubactions.com"
          git config --global user.name "Github Actions"

      - name: Install pip dependencies
        run: |
          pip install .[tools,test]

      - name: Run tests
        run: |
          pytest -v

  run-coverall:
    name: Running tests using miniconda
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: deptest-${{ matrix.python-version }}
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Show conda details
        run: |
          conda info
          conda list
          which python
          conda --version

      - name: Install other conda dependencies
        run: |
          conda install -c conda-forge datalad
          conda install pip pytest

      - name: Configure git-annex
        run: |
          git config --global user.email "BEP032toolsTest@githubactions.com"
          git config --global user.name "Github Actions"

      - name: Install pip dependencies
        run: |
          pip install .[tools,test]
          pip install coveralls

      - name: Create coverage
        run: coverage run --source=bep032tools -m pytest bep032tools/

      - name: Submit to coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
